$ErrorActionPreference='Stop'
$project='C:\project\musicjlpt\projects\naze-nazo-answer'
$framesPath=Join-Path $project 'project\frames.json'; $lexPath=Join-Path $project 'project\proposals\lexical.json'
$frameBytes=[System.IO.File]::ReadAllBytes($framesPath); $sha=([System.Security.Cryptography.SHA256]::Create().ComputeHash($frameBytes)|ForEach-Object{$_.ToString('x2')})-join ''
$lexBytes=[System.IO.File]::ReadAllBytes($lexPath); $lexSha=([System.Security.Cryptography.SHA256]::Create().ComputeHash($lexBytes)|ForEach-Object{$_.ToString('x2')})-join ''
$frames=(Get-Content -Raw -Encoding utf8 $framesPath|ConvertFrom-Json).frames
$lex=Get-Content -Raw -Encoding utf8 $lexPath|ConvertFrom-Json
$lineZh=@{
'l001'='（NaNaNaNa）为什么？为什么？WHY？';'l002'='NaNaNaNa，谜？谜！ANSWER？！';'l003'='把点与点连起来，哎呀？哎呀！';'l004'='「花丸式完美解决！」吗？吗？';'l005'='推理和谜题如镜像般相反，反复翻转，最终逆转。';'l006'='连言语和举止都是诱饵？陷阱！可不能轻信，不行！不行！';'l007'='仔细看，认真想，然后迈出第一步。';'l008'='看到有困难的人，就想立刻帮忙。';'l009'='因为无论如何都想做点什么，正飞奔而出。';'l010'='Na Na Na，谜！谜！解开谜团的就是名侦探☆';'l012'='Na Na Na，为什么？为什么？和大家在一起，勇气百倍。';'l013'='汇集力量，跨越过去；朋友是奇迹的集合。';'l014'='出发吧！名侦探☆';'l015'='把点和线连起来，看吧！看吧？！';'l016'='「花丸式完美解决」也许？也许？箭头已经指向答案。';'l017'='痛快！愉快！爽快！';'l018'='可是呢、但是呢，有些事解不开——那是心里的迷宫。';'l019'='秘密之门不是靠撬开；只要陪伴在旁就好，抱歉。';'l020'='当看到受伤的人时，不靠言语……';'l021'='想一直、比任何人都更在你身边，做你的同伴。';'l022'='Na Na Na，谜！谜！解开谜团的就是名侦探☆';'l023'='越是追赶，越会逃走；这是充满矛盾的谜团。';'l024'='Na Na Na，为什么？为什么？只要和大家在一起，元气百倍。';'l025'='失误不会就此结束；和朋友一起回收伏笔。';'l026'='出发吧！名侦探☆';'l027'='所谓正确，会因人而异，不过……';'l028'='温柔的话会传达出去吗？想把暖洋洋的心动传递给你。';'l029'='在勇气之后，能看见希望。沙啦啦啦。';'l030'='朋友是闪耀的宝石；每一个人、每一个人，大家都在发光☆';'l031'='Na Na Na，谜！谜！解开谜团的就是名侦探☆';'l033'='Na Na Na，为什么？为什么？和大家在一起，勇气百倍。';'l034'='汇集力量，跨越过去；朋友是奇迹的集合。';'l035'='出发吧！名侦探☆';'l036'='Na Na Na，为什么？为什么？和大家在一起，勇气千倍。';'l037'='和朋友手牵着手，直到万事解决为止！';'l038'='因为是光之美少女☆（NaNaNaNa，为什么？谜？！ANSWER！）'}
$meaning=@{'なぜ'='为什么';'なぞ'='谜；谜题';'点'='点';'結んだら'='连接后；如果连接起来';'あら'='哎呀；哎哟';'はなまる'='花丸；满分、完美';'解決'='解决';'推理'='推理';'謎'='谜；谜团';'うら返し'='相反面；反转';'二転三転'='反复变化；一波三折';'逆転'='逆转';'言葉'='言语；话语';'仕草'='举止；动作';'罠'='陷阱；圈套';'うのみにしては'='若照单全收的话；若轻信的话';'だめ'='不行；不可';'よく'='仔细地；充分地';'みて'='看着；看一看';'考えて'='思考后；认真想';'それから'='然后；之后';'踏み出す'='迈出；踏出';'1歩'='一步';'困っている'='正遇到困难；为难';'人'='人';'見たら'='看到……时；如果看见';'すぐに'='立刻；马上';'助けたい'='想帮助；想救助';'だって'='因为；毕竟';'何とか'='无论如何；设法';'何とかしたくて'='无论如何都想做点什么';'駈け出している'='正飞奔而出';'解く'='解开；解答';'名探偵'='名侦探';'うそ'='谎言';'まごこと'='真伪；真相（按 QRC 原文）';'見極めて'='辨明后；看清后';'笑顔'='笑容';'答え'='答案';'見つける'='找到；发现';'みんな'='大家；所有人';'いると'='和……在一起时';'勇気'='勇气';'100倍'='一百倍';'ちから合わせて'='齐心协力；汇集力量';'乗り超える'='跨越；克服';'友'='朋友';'キセキ'='奇迹';'かたまり'='一团；集合体';'行く'='去；出发';'線'='线';'つなげたら'='连接起来后；如果连接';'ほら'='你看；瞧';'矢印'='箭头';'もう'='已经；早已';'指す'='指向；指出';'痛快'='痛快';'愉快'='愉快';'爽快'='爽快';'だけど'='但是；不过';'でも'='但是；不过';'解き明かせない'='无法解开；无法弄明白';'それ'='那个；那件事';'心'='心；内心';'迷宮'='迷宫';'秘密'='秘密';'鍵'='钥匙';'こじ開けない'='不撬开；不强行打开';'寄り添う'='陪伴在旁；依偎';'ごめん'='抱歉；对不起';'傷付いてる'='正在受伤；受了伤';'居ると'='有……时；当……在时';'コトバ'='言语；话语';'ずっと'='一直；始终';'そばで'='在身边；在旁边';'誰より'='比任何人都……';'味方でいたい'='想做你的同伴；想站在你这边';'追えば'='若追赶；一追';'追うほど'='越追越……';'逃げていく'='逃离而去；越发逃开';'ムジュン'='矛盾';'だらけ'='满是；尽是';'ミステリー'='谜团；悬疑';'いれば'='只要在一起；如果在';'元気'='元气；精神';'ミス'='失误；错误';'終わらない'='不会结束；不会到此为止';'伏線回収'='回收伏笔；收束伏笔';'正しさって'='所谓的正确';'人によって'='因人而异';'変わるけど'='会不同，不过……';'やさしさなら'='如果是温柔；说到温柔';'びくかな'='会传达出去吗？（按 QRC 原文）';'ポカポカ'='暖洋洋；暖乎乎';'ときゅんきゅん'='和怦然心动';'届けたい'='想传递；想送达';'あと'='之后；后面';'見えてくる'='逐渐显现；开始看得见';'キボウ'='希望';'シャラララ'='沙啦啦啦（拟声）';'友だち'='朋友';'光る'='闪耀；发光';'ジュエル'='宝石';'1人'='一个人；每一个人';'みんなで'='大家一起';'輝いてる'='正在闪耀；闪闪发光';'手に手をとって'='手牵着手；携手';'万事解決するまで'='直到万事解决为止';'プリキュア'='光之美少女'}
$meaning['1000倍']='一千倍'
$function=@{'と'='连接并列对象；表示“和”';'を'='提示动作对象';'は'='提示主题；作对比';'や'='列举事物（……和……等）';'さえ'='强调极端例子（连……也）';'の'='连接修饰成分；表示所属';'よ'='加强语气；告知对方';'かな'='句末自问或不确定确认（……吗／……吧）';'が'='提示主语；强调焦点';'か'='表示选择或疑问';'かも'='表示不确定推测（也许）';'ね'='征求共鸣；缓和语气';'だけで'='限定条件（只要……就）';'じゃなくって'='否定前项并作连接（不是……而是……）';'では'='表示状态／条件；构成“ではない”';'ば'='表示假定条件（如果……）';'まで'='表示终点（直到……为止）'}
$changes=[System.Collections.Generic.List[object]]::new()
function Change($id,$field,$old,$new,$reason){$changes.Add([ordered]@{frameId=$id;field=$field;old=$old;new=$new;confidence=0.94;evidence=@($reason);changesTokenStructure=$false})}
foreach($f in $frames){if($f.id -notin @('l011','l032')){Change $f.id 'caption.translationZh' $f.caption.translationZh $lineZh[$f.id] 'QQ Music Chinese track reconciled with reviewed Japanese wording and song context.'}}
foreach($x in ($lex.changes|Where-Object{$_.field -eq 'grammarCards'})){
  $newCards=@();foreach($card in $x.new){$c=[ordered]@{};$card.psobject.Properties|ForEach-Object{$c[$_.Name]=$_.Value};$token=[string]$c.token
    if($function.ContainsKey($token)){$c.Remove('zhMeaning');$c['functionZh']=$function[$token]}elseif($meaning.ContainsKey($token)){$c.Remove('functionZh');$c['zhMeaning']=$meaning[$token]}else{throw "Missing aligned translation for $($x.frameId) / $token"};$newCards += [pscustomobject]$c}
  Change $x.frameId 'grammarCards' $x.new $newCards 'Aligned to lexical.json final grammarCards; meanings/functions reflect the QQ Chinese line and local syntax.'
}
$out=[ordered]@{schemaVersion=2;reviewRole='translation-aligned';scope=[ordered]@{frameIds=@($frames|ForEach-Object{$_.id})};baseFrameSha256=$sha;alignsTo=[ordered]@{file='project/proposals/lexical.json';sha256=$lexSha};changes=@($changes)}
$out|ConvertTo-Json -Depth 12|Set-Content -Encoding utf8NoBOM (Join-Path $project 'project\proposals\translation-aligned.json')
Write-Output "wrote $($changes.Count) aligned changes"
