"use strict";
const crypto=require("crypto"),fs=require("fs"),path=require("path");
const {qrc,lrc}=require("C:/project/musicjlpt/tmp-qrc/node_modules/smart-lyric/dist/index.js");
const ROOT=path.resolve(__dirname,"../.."),SOURCE=path.join(ROOT,"source"),TIMING=path.join(ROOT,"project","timing"); fs.mkdirSync(TIMING,{recursive:true});
const sha=p=>crypto.createHash("sha256").update(fs.readFileSync(p)).digest("hex");
const write=(n,v)=>fs.writeFileSync(path.join(TIMING,n),JSON.stringify(v,null,2)+"\n","utf8");
function kara(source,output){const decoded=qrc.decrypt(fs.readFileSync(path.join(SOURCE,source)));if(!decoded)throw Error(`decode failed ${source}`);const parsed=qrc.parse(decoded);const lines=parsed.content.map((line,i)=>{let offset=0;const parts=line.content.map((part,j)=>{const text=part.content,item={text,startMs:line.start+part.start,endMs:line.start+part.start+part.duration,sourceOffset:offset,sourcePartIndex:j};offset+=text.length;return item});return{id:`${output}-${String(i+1).padStart(3,"0")}`,startMs:line.start,endMs:line.start+line.duration,text:parts.map(p=>p.text).join(""),parts}}).filter(x=>x.text.trim());write(output,{schemaVersion:1,source,lyricType:"karaoke",lines});fs.writeFileSync(path.join(TIMING,output.replace(".json","-decoded.qrc")),decoded,"utf8");return{count:lines.length,minMs:lines[0]?.startMs??null,maxMs:lines.at(-1)?.endMs??null}}
function regular(source,output){const decoded=qrc.decrypt(fs.readFileSync(path.join(SOURCE,source)));if(!decoded)throw Error(`decode failed ${source}`);const parsed=lrc.parse(decoded);const lines=parsed.content.map((line,i)=>({id:`translation-${String(i+1).padStart(3,"0")}`,startMs:line.start,text:line.content})).filter(x=>x.text.trim());write(output,{schemaVersion:1,source,lyricType:"regular",lines});fs.writeFileSync(path.join(TIMING,"translation-decoded.qrc"),decoded,"utf8");return{count:lines.length,minMs:lines[0]?.startMs??null,maxMs:lines.at(-1)?.startMs??null}}
const report={schemaVersion:1,decoder:"smart-lyric 1.0.1 locked local runtime",sourceHashes:Object.fromEntries(["lyrics.qm.qrc","lyrics.qmRoma.qrc","lyrics.qmts.qrc"].map(x=>[x,sha(path.join(SOURCE,x))])),outputs:{qm:kara("lyrics.qm.qrc","qm.json"),roma:kara("lyrics.qmRoma.qrc","roma.json"),translation:regular("lyrics.qmts.qrc","translation.json")},validation:{utf8:true,wordTimingAvailable:true,status:"passed"}};write("decode-report.json",report);
